name: 🚀 Release Trigger TEST

on:
  push:
    branches:
      - test-release-trigger

jobs:
  call-release-trigger:
    uses: ynput/ops-repo-automation/.github/workflows/release_trigger_cpp.yml@develop

    with:
      draft: true
      release_overwrite: "99.0.0-test.1"

    secrets:
      token: ${{ secrets.YNPUT_BOT_TOKEN }}
      email: ${{ secrets.CI_EMAIL }}
      user: ${{ secrets.CI_USER }}
